[package]
name = "pymde-knn"
version = "0.1.0"
edition = "2024"

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
rayon = "1.10"
rand = "0.9"
rand_chacha = "0.9"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
strip = "symbols"
codegen-units = 1
